version: 2.0.0-beta6-{build}
image: Visual Studio 2019

branches:
  only:
    - master
    - dev
    - tests

build_script:
  - ps: .\build.ps1 -target=Pack

test_script:
  - ps: .\build.ps1 -target=Test
